### ISSUE TITLE
no-ss 国内网站都上不了

### ISSUE THREAD

**Issue by trigsoft** [gxfxyz/unblockchn#11]
Hi,

set-up --no-ss运行之后国内网站都访问不了了。我删掉底下这个规则就可以了。
iptables -t nat -D PREROUTING -p tcp -m set --match-set chn dst -j REDIRECT --to-port 1080

**Comment by gxfxyz** [comment]
你好，

此工具的[原理](https://github.com/gxfxyz/unblockchn#原理)是需要通过 ss-redir 来实现的，`python3 unblockchn.py router setup --no-ss` 会跳过配置 ss-redir，如果之前没有配置过 ss-redir，那么在 chn ipset 里的国内网站 IP 肯定就会无法访问。第一次还是需要用 `python3 unblockchn.py router setup` 命令来完整配置路由器，这样才能生效。
