### ISSUE TITLE
电脑好像没问题了，手机上的APP依然有限制

### ISSUE THREAD

**Issue by wuhongle** [gxfxyz/unblockchn#2]
国内ss服务器搭建好了，家里路由器也设置好了，但是连上同一个路由的电脑没有版权限制了，手机上访问uku.im/check 也显示true，但是手机的腾讯视频app和优酷app都一直提示版权问题

加了一个 v.qq.com解决了。

**Comment by gxfxyz** [comment]
因为 Unblock Youku 的规则主要是针对浏览器 Web 端，手机端 App 有可能会采用不同的检测，所以可能需要手动添加一些规则。
