### ISSUE TITLE
希望和padavan上的fakeinchina一样加入多个SS服务器

### ISSUE THREAD

**Issue by jackiejtr** [gxfxyz/unblockchn#3]
可以故障转移切换之类的 万分感谢

**Comment by jackiejtr** [comment]
https://github.com/gaocuo/fic

**Comment by gxfxyz** [comment]
好的，我有空研究下怎么实现好。

**Comment by gxfxyz** [comment]
已实现 (7dd79af015d87d674cee2f7929efee97f83df84f)，请更新到最新版。
