### ISSUE TITLE
生成PAC和ACL

### ISSUE THREAD

**Issue by szhu25** [gxfxyz/unblockchn#6]
您好，

我刚才对这个程序进行了一点小改动，添加了常规PAC和ACL文件 （给SS和其他软件用）， 请问可以添加到您这边代码内吗？

**Comment by gxfxyz** [comment]
👍 欢迎添砖加瓦，发个 pull request 给我吧。

**Comment by szhu25** [comment]
@gxfxyz 已经打开😁
