### ISSUE TITLE
时常解锁失效，需restore后重新setup才可修复

### ISSUE THREAD

**Issue by chudeyang0225** [gxfxyz/unblockchn#8]
如题，on/off指令也似乎无效。不清楚是什么原因
平台：AC88u，改版梅林7.9.1

建议：鉴于目前故障原因未知，妥协方案为增加一个reset选项，连续执行restore和setup。通过指令行或shortcuts一键执行修复。

**Comment by gxfxyz** [comment]
你好，感谢反馈 👍 

我用的是原版的 Asuswrt-Merlin，没有遇到你所描述的问题，所以我怀疑是你使用的改版梅林（指的是 koolshare 改版是吗？）附加的某个功能或者插件覆盖了 Unblock CHN 所使用的 dnsmasq 或者 ipset 规则，从而导致 Unblock CHN 功能失效。如果是这种原因的话，还是找出具体冲突的地方，然后再想办法规避掉比较好，我不想专门再加个命令来手动临时修复。

麻烦你下次再遇到解锁失效的时候，进行以下检查，把结果发给我，你如果有开启什么插件功能也列给我，看看能不能具体定位是哪里出问题了。

1. 检查 ss-redir 是否正常运行中：

```console
$ ps | grep ss-redir
```

2. 检查 dnsmasq 是否正常运行中：

```console
$ ps | grep dnsmasq
```

3. 检查 dnsmasq 配置：

```console
$ cat /etc/dnsmasq.conf
```

4. 检查 dnsmasq.conf.add：

```console
$ cat /jffs/configs/dnsmasq.conf.add
```

5. 检查 ipset 规则：

```console
$ ipset list chn
```

6. 检查 iptables 规则：

```console
$ iptables -S -t nat
```

**Comment by gxfxyz** [comment]
由于长时间无更新，此 issue 暂时关闭。
